name: Deploy Flutter Web to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Resolve Dependencies
        run: flutter pub get

      - name: Build Web Release
        run: flutter build web --release

      - name: Copy Vercel Configuration
        # We copy the vercel.json configuration from the root to build/web so that Vercel
        # uses it during static deployment to route deep links to index.html
        run: cp vercel.json build/web/

      - name: Deploy static build to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./build/web
          vercel-args: '--prod'
